'use client'
import { useState, useEffect } from 'react'
import { PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, ResponsiveContainer } from 'recharts'
import { Wallet, TrendingUp, Target, AlertTriangle, Bot } from 'lucide-react'
import { getFinanceData } from '@/lib/dataManager'

const COLORS = ['#00ff88', '#0088ff', '#8800ff', '#ff0088', '#ffaa00']

export default function Dashboard() {
  const [expenses, setExpenses] = useState([
    { name: 'Food', value: 3400, color: '#00ff88' },
    { name: 'Transport', value: 1200, color: '#0088ff' },
    { name: 'Bills', value: 2800, color: '#8800ff' },
    { name: 'Shopping', value: 1400, color: '#ff0088' },
    { name: 'Rent', value: 8000, color: '#aa00ff' }
  ])

  const [monthlyIncome, setMonthlyIncome] = useState(25000)
  const [monthlyRent, setMonthlyRent] = useState(8000)

  const loadData = () => {
    const data = getFinanceData()
    setMonthlyIncome(data.user.monthlyIncome)
    setMonthlyRent(data.user.monthlyRent)
    
    const categoryTotals = data.expenses.reduce((acc: any, exp: any) => {
      acc[exp.category] = (acc[exp.category] || 0) + exp.amount
      return acc
    }, {})
    
    const chartData = Object.entries(categoryTotals).map(([name, value], index) => ({
      name,
      value: value as number,
      color: ['#00ff88', '#0088ff', '#8800ff', '#ff0088', '#aa00ff'][index % 5]
    }))
    
    chartData.push({ name: 'Rent', value: data.user.monthlyRent, color: '#aa00ff' })
    setExpenses(chartData)
  }

  useEffect(() => {
    loadData()
    
    const handleStorageChange = () => loadData()
    window.addEventListener('storage', handleStorageChange)
    
    return () => window.removeEventListener('storage', handleStorageChange)
  }, [])

  const [monthlyData] = useState([
    { month: 'Jan', income: monthlyIncome, expenses: 18000 },
    { month: 'Feb', income: monthlyIncome, expenses: 19500 },
    { month: 'Mar', income: monthlyIncome, expenses: 17800 }
  ])

  const totalExpenses = expenses.reduce((sum, item) => sum + item.value, 0)
  const savings = monthlyIncome - totalExpenses

  const downloadReport = async () => {
    const { jsPDF } = await import('jspdf')
    const data = getFinanceData()
    const currentUser = JSON.parse(localStorage.getItem('currentUser') || '{}')
    
    const doc = new jsPDF()
    
    // Header
    doc.setFontSize(20)
    doc.text('CAI Finance - Monthly Report', 20, 30)
    
    doc.setFontSize(12)
    doc.text(`User: ${currentUser.name || 'User'}`, 20, 50)
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 60)
    
    // Financial Summary
    doc.setFontSize(16)
    doc.text('FINANCIAL SUMMARY', 20, 80)
    
    doc.setFontSize(12)
    doc.text(`Monthly Income: Rs.${monthlyIncome.toLocaleString()}`, 20, 100)
    doc.text(`Total Expenses: Rs.${totalExpenses.toLocaleString()}`, 20, 110)
    doc.text(`Net Savings: Rs.${savings.toLocaleString()}`, 20, 120)
    doc.text(`Savings Rate: ${((savings / monthlyIncome) * 100).toFixed(1)}%`, 20, 130)
    
    // Expense Breakdown
    doc.setFontSize(16)
    doc.text('EXPENSE BREAKDOWN', 20, 150)
    
    doc.setFontSize(12)
    let yPos = 170
    expenses.forEach(exp => {
      doc.text(`${exp.name}: Rs.${exp.value.toLocaleString()}`, 20, yPos)
      yPos += 10
    })
    
    // AI Insights
    doc.setFontSize(16)
    doc.text('AI INSIGHTS', 20, yPos + 20)
    
    doc.setFontSize(12)
    yPos += 40
    doc.text(`Your savings rate is ${((savings / monthlyIncome) * 100).toFixed(1)}%`, 20, yPos)
    yPos += 10
    doc.text(savings > 0 ? 'Good job maintaining positive savings!' : 'Consider reducing expenses.', 20, yPos)
    yPos += 10
    doc.text('Focus on largest expense categories for optimization', 20, yPos)
    
    // Footer
    doc.setFontSize(10)
    doc.text('Generated by CAI Finance App', 20, 280)
    
    doc.save(`finance-report-${new Date().toISOString().split('T')[0]}.pdf`)
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-black to-gray-900 text-white p-6">
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold mb-2 bg-gradient-to-r from-green-400 to-blue-500 bg-clip-text text-transparent">
            CAI Finance Dashboard
          </h1>
          <p className="text-gray-400">AI-Powered Personal Finance Manager for Citizens</p>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
          <div className="bg-black/40 backdrop-blur-lg border border-green-500/20 rounded-xl p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-gray-400 text-sm">Monthly Income</p>
                <p className="text-2xl font-bold text-green-400">₹{monthlyIncome.toLocaleString()}</p>
              </div>
              <Wallet className="w-8 h-8 text-green-400" />
            </div>
          </div>

          <div className="bg-black/40 backdrop-blur-lg border border-red-500/20 rounded-xl p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-gray-400 text-sm">Total Expenses</p>
                <p className="text-2xl font-bold text-red-400">₹{totalExpenses.toLocaleString()}</p>
              </div>
              <TrendingUp className="w-8 h-8 text-red-400" />
            </div>
          </div>

          <div className="bg-black/40 backdrop-blur-lg border border-blue-500/20 rounded-xl p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-gray-400 text-sm">Savings</p>
                <p className="text-2xl font-bold text-blue-400">₹{savings.toLocaleString()}</p>
              </div>
              <Target className="w-8 h-8 text-blue-400" />
            </div>
          </div>

          <div className="bg-black/40 backdrop-blur-lg border border-yellow-500/20 rounded-xl p-6">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-gray-400 text-sm">Budget Left</p>
                <p className="text-2xl font-bold text-yellow-400">₹{(monthlyIncome * 0.8 - totalExpenses).toLocaleString()}</p>
              </div>
              <AlertTriangle className="w-8 h-8 text-yellow-400" />
            </div>
          </div>
        </div>

        {/* Charts Section */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
          {/* Expense Breakdown */}
          <div className="bg-black/40 backdrop-blur-lg border border-white/10 rounded-xl p-6">
            <h3 className="text-xl font-bold mb-4 text-green-400">Expense Breakdown</h3>
            <div className="h-64">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={expenses}
                    cx="50%"
                    cy="50%"
                    outerRadius={80}
                    fill="#8884d8"
                    dataKey="value"
                    label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                  >
                    {expenses.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* Monthly Comparison */}
          <div className="bg-black/40 backdrop-blur-lg border border-white/10 rounded-xl p-6">
            <h3 className="text-xl font-bold mb-4 text-blue-400">Income vs Expenses</h3>
            <div className="h-64">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={monthlyData}>
                  <XAxis dataKey="month" />
                  <YAxis />
                  <Bar dataKey="income" fill="#00ff88" />
                  <Bar dataKey="expenses" fill="#ff0088" />
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </div>

        {/* AI Insights */}
        <div className="bg-black/40 backdrop-blur-lg border border-purple-500/20 rounded-xl p-6">
          <div className="flex items-center mb-4">
            <Bot className="w-6 h-6 text-purple-400 mr-2" />
            <h3 className="text-xl font-bold text-purple-400">AI Financial Advisor</h3>
          </div>
          <div className="space-y-3">
            <div className="bg-purple-500/10 border border-purple-500/20 rounded-lg p-4">
              <p className="text-sm">💡 <strong>Smart Tip:</strong> You spent ₹900 more on food this month. Consider cooking at home 2 more days per week to save ₹600 monthly.</p>
            </div>
            <div className="bg-green-500/10 border border-green-500/20 rounded-lg p-4">
              <p className="text-sm">✅ <strong>Good Job:</strong> Your savings increased by 15% compared to last month. Keep it up!</p>
            </div>
            <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-4">
              <p className="text-sm">⚠️ <strong>Alert:</strong> Transport expenses are 25% higher than recommended. Try using public transport twice a week.</p>
            </div>
          </div>
        </div>

        {/* Quick Actions */}
        <div className="mt-8 grid grid-cols-2 md:grid-cols-4 gap-4">
          <button className="bg-green-500/20 border border-green-500/30 rounded-lg p-4 hover:bg-green-500/30 transition-all">
            <span className="text-green-400 font-semibold">Add Expense</span>
          </button>
          <button className="bg-blue-500/20 border border-blue-500/30 rounded-lg p-4 hover:bg-blue-500/30 transition-all">
            <span className="text-blue-400 font-semibold">Set Budget</span>
          </button>
          <button className="bg-purple-500/20 border border-purple-500/30 rounded-lg p-4 hover:bg-purple-500/30 transition-all">
            <span className="text-purple-400 font-semibold">AI Advice</span>
          </button>
          <button 
            onClick={downloadReport}
            className="bg-yellow-500/20 border border-yellow-500/30 rounded-lg p-4 hover:bg-yellow-500/30 transition-all"
          >
            <span className="text-yellow-400 font-semibold">Download Report</span>
          </button>
        </div>
      </div>
    </div>
  )
}